version: "3.3"

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/configs/flaskblog.conf.template:/etc/nginx/templates/flaskblog.conf.template
      - ./nginx/data/certbot/conf:/etc/letsencrypt
      - ./nginx/data/certbot/www:/var/www/certbot
    env_file: .env
    depends_on:
      - flaskblog

  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - ./nginx/data/certbot/conf:/etc/letsencrypt
      - ./nginx/data/certbot/www:/var/www/certbot

  flaskblog:
    build: .
    container_name: flaskblog
    restart: always
#    ports:
#      - 5000:5000
    volumes:
      - .:/app
